### Get all users
GET http://localhost:3000/api/v1/users

### Get user by ID
GET http://localhost:3000/api/v1/users/7af25707-9092-4a9b-8853-ee30f57f7bf8

### Create new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doedsadsaf@gmail.com",
  "password": "password123"
}

### Update user
PUT http://localhost:3000/api/v1/users/7fba5076-d227-4ead-868c-3a529240b00b
Content-Type: application/json

{
  "name": "John Doe Updated",
  "email": "john.doe.updated@example.com",
  "password": "newpassword123"
}

### Delete user
DELETE http://localhost:3000/api/v1/users/7af25707-9092-4a9b-8853-ee30f57f7bf8
