// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"

	"sql"
)

type Category struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type Product struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Price      float64        `json:"price"`
	CategoryID sql.NullString `json:"category_id"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserActivity struct {
	UserID    string `json:"user_id"`
	ProductID string `json:"product_id"`
	Action    string `json:"action"`
}
